language: go
go:
  - stable
  - 1.x
  - 1.13.x
  - 1.14.x

install: true

services:
  - docker

env:
  - GO111MODULE=on

before_script:
  - go get gotest.tools/gotestsum

script:
  - go mod verify
  - go mod tidy
  - scripts/checks.sh
  - go vet ./...
  - gotestsum --format short-verbose ./...

